addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.9.4")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.5")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.1.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.15")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
